project:
  type: book
  output-dir: docs

book:
  title: "Changes in forest cover and carbon density in the Upper Marikina RBPL"
  date: last-modified
  chapters:
    - index.qmd
    - part: 10_forest_metrics.qmd
      chapters:
        - 11_tree_height.qmd
        - 12_cci_map.qmd
        - 13_ornl_map.qmd
        - 14_harris_map.qmd
    - part: 20_environment.qmd
      chapters:
        - 21_topography.qmd
        - 22_climate.qmd
    - part: 30_socioeco.qmd
      chapters:
        - 31_tmf.qmd
        - 32_lulc.qmd
        - 33_roads.qmd
        - 34_population.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual

# execute:
#   cache: true
